# Site settings
title: Creco's 끄적크적
tag_text: Creco's 끄적크적
description: A responsive template for publishing single-page websites, articles that are easy on the eyes

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
